server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    username: 'canok'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    baseUrl: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka