server:
  port: 8082
spring:
  application:
    name: notification

  datasource:
    username: 'canok'
    password: 'password'
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672
  zipkin:
    baseUrl: http://zipkin:9411

rabbitmq:
  exchange:
    internal: internal.exchange
  queue:
    name: notification.queue
  routing-keys:
    internal-notification: internal.notification.routingKey

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true